# All Trading Pairs - Data Analysis

In [6]:
import pandas as pd

# Load Data/all_trading_pairs.csv

all_trading_pairs = pd.read_csv('Data/all_trade_pairs.csv')

# Find Count trading pairs that have more than 1 record
# resulting in a dataframe with the trading pairs and the count of records
trading_pairs_count = all_trading_pairs.groupby('potential_pair').size().reset_index(name='counts')
# Sort the dataframe by the counts column
trading_pairs_count = trading_pairs_count.sort_values(by='counts', ascending=False)

trading_pairs_count

       potential_pair  counts
2461        MEDP:SMCI      98
724         ASND:NNDM      90
729          ASND:PFE      85
708           ASND:KO      85
689         ASND:FOLD      84
...               ...     ...
12     000001.SS:AMZN       1
28       000001.SS:CB       1
29      000001.SS:CCI       1
30       000001.SS:CI       1
31    000001.SS:CMCSA       1

[2836 rows x 2 columns]

In [7]:
# Given all_trading_pairs, find trading pairs that have more than 1 record and that have a period_days of
# less than or equal to 20.
trading_pairs_count = all_trading_pairs[all_trading_pairs['period_days'] <= 60].groupby('potential_pair').size().reset_index(name='counts')

trading_pairs_count

       potential_pair  counts
0      000001.SS:ADBE       1
1       000001.SS:APD       1
2      000001.SS:IRTC       1
3     000001.SS:XAK=F       1
4           AAOI:ASND       1
...               ...     ...
1862             YY:T       2
1863          ZM:^XAX       1
1864       ^DJI:^IXIC       1
1865          ^GSPC:T       1
1866        ^NYA:^XAX       1

[1867 rows x 2 columns]